version: '3'

services:
  web:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped 
    volumes:
      - /var/www:/usr/share/nginx/html
    ports:
      - "80:80"

  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
    portainer_data: 
